version: '3.1'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: SHAHADAT
      MONGO_INITDB_ROOT_PASSWORD: SHAHADATpass2456
    ports:
      - '27017:27017'
    volumes:
      - 'my_mongodb_data:/data/db'
volumes:
  my_mongodb_data:
    driver: local
